gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AK.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/AK.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AK.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/AK-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AL.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/AL.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AL.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/AL-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AR.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/AR.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AR.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/AR-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AS.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/AS.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AS.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/AS-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AZ.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/AZ.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/AZ.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/AZ-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/CA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/CA.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/CA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/CA-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/CO.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/CO.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/CO.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/CO-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/CT.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/CT.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/CT.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/CT-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/DC.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/DC.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/DC.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/DC-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/DE.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/DE.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/DE.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/DE-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/FL.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/FL.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/FL.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/FL-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/GA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/GA.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/GA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/GA-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/GU.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/GU.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/GU.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/GU-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/HI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/HI.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/HI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/HI-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/IA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/IA.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/IA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/IA-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/ID.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/ID.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/ID.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/ID-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/IL.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/IL.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/IL.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/IL-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/IN.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/IN.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/IN.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/IN-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/KS.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/KS.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/KS.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/KS-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/KY.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/KY.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/KY.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/KY-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/LA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/LA.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/LA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/LA-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/MA.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/MA-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MD.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/MD.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MD.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/MD-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/ME.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/ME.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/ME.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/ME-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/MI.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/MI-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MN.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/MN.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MN.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/MN-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MO.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/MO.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MO.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/MO-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MP.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/MP.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MP.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/MP-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MS.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/MS.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MS.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/MS-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MT.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/MT.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/MT.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/MT-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NC.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/NC.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NC.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/NC-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/ND.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/ND.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/ND.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/ND-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NE.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/NE.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NE.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/NE-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NH.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/NH.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NH.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/NH-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NJ.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/NJ.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NJ.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/NJ-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NM.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/NM.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NM.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/NM-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NV.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/NV.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NV.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/NV-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NY.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/NY.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/NY.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/NY-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/OH.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/OH.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/OH.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/OH-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/OK.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/OK.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/OK.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/OK-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/OR.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/OR.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/OR.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/OR-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/PA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/PA.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/PA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/PA-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/PR.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/PR.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/PR.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/PR-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/RI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/RI.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/RI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/RI-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/SC.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/SC.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/SC.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/SC-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/SD.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/SD.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/SD.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/SD-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/TN.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/TN.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/TN.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/TN-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/TX.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/TX.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/TX.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/TX-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/UT.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/UT.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/UT.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/UT-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/VA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/VA.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/VA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/VA-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/VI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/VI.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/VI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/VI-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/VT.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/VT.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/VT.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/VT-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/WA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/WA.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/WA.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/WA-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/WI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/WI.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/WI.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/WI-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/WV.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/WV.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/WV.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/WV-hydro-patched.tif -r cubicspline -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/WY.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-raised-460.tif ./dems/7-5-arc-second-clipped-500m/WY.tif -r cubicspline -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 500 500 -tap -cutline ./tl_2022_us_state/split_individual/WY.gpkg -crop_to_cutline ./dems/dems-ready-to-cut/7-5-arc-second-merged-500m-width-hydro-patched-raised-400.tif C:/Users/ansonl/development/dem-to-stl-workflow/dems/7-5-arc-second-clipped-500m-hydro-patched/WY-hydro-patched.tif -r cubicspline -multi
