gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AK.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/AK.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AK.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/AK.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AL.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/AL.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AL.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/AL.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AR.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/AR.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AR.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/AR.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AS.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/AS.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AS.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/AS.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AZ.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/AZ.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/AZ.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/AZ.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/CA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/CA.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/CA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/CA.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/CO.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/CO.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/CO.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/CO.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/CT.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/CT.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/CT.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/CT.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/DC.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/DC.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/DC.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/DC.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/DE.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/DE.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/DE.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/DE.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/FL.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/FL.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/FL.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/FL.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/GA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/GA.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/GA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/GA.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/GU.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/GU.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/GU.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/GU.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/HI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/HI.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/HI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/HI.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/IA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/IA.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/IA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/IA.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/ID.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/ID.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/ID.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/ID.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/IL.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/IL.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/IL.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/IL.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/IN.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/IN.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/IN.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/IN.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/KS.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/KS.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/KS.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/KS.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/KY.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/KY.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/KY.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/KY.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/LA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/LA.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/LA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/LA.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/MA.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/MA.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MD.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/MD.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MD.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/MD.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/ME.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/ME.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/ME.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/ME.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/MI.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/MI.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MN.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/MN.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MN.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/MN.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MO.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/MO.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MO.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/MO.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MP.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/MP.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MP.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/MP.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MS.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/MS.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MS.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/MS.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MT.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/MT.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/MT.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/MT.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NC.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/NC.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NC.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/NC.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/ND.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/ND.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/ND.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/ND.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NE.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/NE.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NE.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/NE.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NH.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/NH.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NH.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/NH.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NJ.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/NJ.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NJ.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/NJ.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NM.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/NM.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NM.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/NM.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NV.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/NV.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NV.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/NV.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NY.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/NY.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/NY.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/NY.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/OH.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/OH.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/OH.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/OH.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/OK.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/OK.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/OK.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/OK.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/OR.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/OR.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/OR.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/OR.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/PA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/PA.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/PA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/PA.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/PR.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/PR.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/PR.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/PR.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/RI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/RI.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/RI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/RI.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/SC.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/SC.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/SC.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/SC.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/SD.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/SD.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/SD.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/SD.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/TN.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/TN.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/TN.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/TN.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/TX.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/TX.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/TX.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/TX.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/UT.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/UT.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/UT.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/UT.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/VA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/VA.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/VA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/VA.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/VI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/VI.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/VI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/VI.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/VT.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/VT.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/VT.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/VT.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/WA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/WA.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/WA.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/WA.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/WI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/WI.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/WI.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/WI.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/WV.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/WV.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/WV.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/WV.tif -r near -multi
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/WY.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-raised-460m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAIfNotInHydroMaskBAndScaleAt4m-250m-clipped/WY.tif -r near -multi -dstnodata -9999
gdalwarp -overwrite -t_srs ESRI:102004 -of GTiff -tr 250 250 -cutline ./sources/USCB/tl_2022_us_state/split_individual/WY.gpkg -crop_to_cutline ./dem-feature-generation/raiseLandAScaleAt4m-250m-raised-400m.tif C:/Users/ansonl/development/dem-to-stl-workflow/dem-feature-generation/raiseLandAScaleAt4m-250m-clipped/WY.tif -r near -multi
