./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/DC-no-rivers/DC-hydro-patched_tile_1_1.STL ./state_stls/DC/DC_tile_1_1.STL minus ./state_stls/DC/DC_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/RI-no-rivers/RI-hydro-patched_tile_1_1.STL ./state_stls/RI/RI_tile_1_1.STL minus ./state_stls/RI/RI_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/DE-no-rivers/DE-hydro-patched_tile_1_1.STL ./state_stls/DE/DE_tile_1_1.STL minus ./state_stls/DE/DE_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/CT-no-rivers/CT-hydro-patched_tile_1_1.STL ./state_stls/CT/CT_tile_1_1.STL minus ./state_stls/CT/CT_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/NJ-no-rivers/NJ-hydro-patched_tile_1_1.STL ./state_stls/NJ/NJ_tile_1_1.STL minus ./state_stls/NJ/NJ_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/PR-no-rivers/PR-hydro-patched_tile_1_1.STL ./state_stls/PR/PR_tile_1_1.STL minus ./state_stls/PR/PR_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/VT-no-rivers/VT-hydro-patched_tile_1_1.STL ./state_stls/VT/VT_tile_1_1.STL minus ./state_stls/VT/VT_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/NH-no-rivers/NH-hydro-patched_tile_1_1.STL ./state_stls/NH/NH_tile_1_1.STL minus ./state_stls/NH/NH_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/MA-no-rivers/MA-hydro-patched_tile_1_1.STL ./state_stls/MA/MA_tile_1_1.STL minus ./state_stls/MA/MA_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/MD-no-rivers/MD-hydro-patched_tile_1_1.STL ./state_stls/MD/MD_tile_1_1.STL minus ./state_stls/MD/MD_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/IN-no-rivers/IN-hydro-patched_tile_1_1.STL ./state_stls/IN/IN_tile_1_1.STL minus ./state_stls/IN/IN_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/SC-no-rivers/SC-hydro-patched_tile_1_1.STL ./state_stls/SC/SC_tile_1_1.STL minus ./state_stls/SC/SC_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/WV-no-rivers/WV-hydro-patched_tile_1_1.STL ./state_stls/WV/WV_tile_1_1.STL minus ./state_stls/WV/WV_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/OH-no-rivers/OH-hydro-patched_tile_1_1.STL ./state_stls/OH/OH_tile_1_1.STL minus ./state_stls/OH/OH_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/ME-no-rivers/ME-hydro-patched_tile_1_1.STL ./state_stls/ME/ME_tile_1_1.STL minus ./state_stls/ME/ME_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/PA-no-rivers/PA-hydro-patched_tile_1_1.STL ./state_stls/PA/PA_tile_1_1.STL minus ./state_stls/PA/PA_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/MS-no-rivers/MS-hydro-patched_tile_1_1.STL ./state_stls/MS/MS_tile_1_1.STL minus ./state_stls/MS/MS_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/HI-no-rivers/HI-hydro-patched_tile_1_1.STL ./state_stls/HI/HI_tile_1_1.STL minus ./state_stls/HI/HI_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/AR-no-rivers/AR-hydro-patched_tile_1_1.STL ./state_stls/AR/AR_tile_1_1.STL minus ./state_stls/AR/AR_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/IA-no-rivers/IA-hydro-patched_tile_1_1.STL ./state_stls/IA/IA_tile_1_1.STL minus ./state_stls/IA/IA_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/AL-no-rivers/AL-hydro-patched_tile_1_1.STL ./state_stls/AL/AL_tile_1_1.STL minus ./state_stls/AL/AL_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/TN-no-rivers/TN-hydro-patched_tile_1_1.STL ./state_stls/TN/TN_tile_1_1.STL minus ./state_stls/TN/TN_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/ND-no-rivers/ND-hydro-patched_tile_1_1.STL ./state_stls/ND/ND_tile_1_1.STL minus ./state_stls/ND/ND_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/IL-no-rivers/IL-hydro-patched_tile_1_1.STL ./state_stls/IL/IL_tile_1_1.STL minus ./state_stls/IL/IL_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/KY-no-rivers/KY-hydro-patched_tile_1_1.STL ./state_stls/KY/KY_tile_1_1.STL minus ./state_stls/KY/KY_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/LA-no-rivers/LA-hydro-patched_tile_1_1.STL ./state_stls/LA/LA_tile_1_1.STL minus ./state_stls/LA/LA_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/KS-no-rivers/KS-hydro-patched_tile_1_1.STL ./state_stls/KS/KS_tile_1_1.STL minus ./state_stls/KS/KS_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/GA-no-rivers/GA-hydro-patched_tile_1_1.STL ./state_stls/GA/GA_tile_1_1.STL minus ./state_stls/GA/GA_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/WI-no-rivers/WI-hydro-patched_tile_1_1.STL ./state_stls/WI/WI_tile_1_1.STL minus ./state_stls/WI/WI_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/SD-no-rivers/SD-hydro-patched_tile_1_1.STL ./state_stls/SD/SD_tile_1_1.STL minus ./state_stls/SD/SD_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/WA-no-rivers/WA-hydro-patched_tile_1_1.STL ./state_stls/WA/WA_tile_1_1.STL minus ./state_stls/WA/WA_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/NE-no-rivers/NE-hydro-patched_tile_1_1.STL ./state_stls/NE/NE_tile_1_1.STL minus ./state_stls/NE/NE_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/NC-no-rivers/NC-hydro-patched_tile_1_1.STL ./state_stls/NC/NC_tile_1_1.STL minus ./state_stls/NC/NC_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/VA-no-rivers/VA-hydro-patched_tile_1_1.STL ./state_stls/VA/VA_tile_1_1.STL minus ./state_stls/VA/VA_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/MO-no-rivers/MO-hydro-patched_tile_1_1.STL ./state_stls/MO/MO_tile_1_1.STL minus ./state_stls/MO/MO_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/OK-no-rivers/OK-hydro-patched_tile_1_1.STL ./state_stls/OK/OK_tile_1_1.STL minus ./state_stls/OK/OK_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/UT-no-rivers/UT-hydro-patched_tile_1_1.STL ./state_stls/UT/UT_tile_1_1.STL minus ./state_stls/UT/UT_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/WY-no-rivers/WY-hydro-patched_tile_1_1.STL ./state_stls/WY/WY_tile_1_1.STL minus ./state_stls/WY/WY_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/CO-no-rivers/CO-hydro-patched_tile_1_1.STL ./state_stls/CO/CO_tile_1_1.STL minus ./state_stls/CO/CO_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/NY-no-rivers/NY-hydro-patched_tile_1_1.STL ./state_stls/NY/NY_tile_1_1.STL minus ./state_stls/NY/NY_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/MN-no-rivers/MN-hydro-patched_tile_1_1.STL ./state_stls/MN/MN_tile_1_1.STL minus ./state_stls/MN/MN_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/NM-no-rivers/NM-hydro-patched_tile_1_1.STL ./state_stls/NM/NM_tile_1_1.STL minus ./state_stls/NM/NM_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/AZ-no-rivers/AZ-hydro-patched_tile_1_1.STL ./state_stls/AZ/AZ_tile_1_1.STL minus ./state_stls/AZ/AZ_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/OR-no-rivers/OR-hydro-patched_tile_1_1.STL ./state_stls/OR/OR_tile_1_1.STL minus ./state_stls/OR/OR_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/ID-no-rivers/ID-hydro-patched_tile_1_1.STL ./state_stls/ID/ID_tile_1_1.STL minus ./state_stls/ID/ID_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/MI-no-rivers/MI-hydro-patched_tile_1_1.STL ./state_stls/MI/MI_tile_1_1.STL minus ./state_stls/MI/MI_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/NV-no-rivers/NV-hydro-patched_tile_1_1.STL ./state_stls/NV/NV_tile_1_1.STL minus ./state_stls/NV/NV_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/MT-no-rivers/MT-hydro-patched_tile_1_1.STL ./state_stls/MT/MT_tile_1_1.STL minus ./state_stls/MT/MT_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/FL-no-rivers/FL-hydro-patched_tile_1_1.STL ./state_stls/FL/FL_tile_1_1.STL minus ./state_stls/FL/FL_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/CA-no-rivers/CA-hydro-patched_tile_1_1.STL ./state_stls/CA/CA_tile_1_1.STL minus ./state_stls/CA/CA_rivers.STL
./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/TX-no-rivers/TX-hydro-patched_tile_1_1.STL ./state_stls/TX/TX_tile_1_1.STL minus ./state_stls/TX/TX_rivers.STL
#./gp-cli/precompiled/pc/bin/meshboolean.exe ./state_stls/AK-no-rivers/AK-hydro-patched_tile_1_1.STL ./state_stls/AK/AK_tile_1_1.STL minus ./state_stls/AK/AK_rivers.STL
