python ./TouchTerrain_standalone.py ./touch_terrain_configs/DC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/DC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/RI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/RI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/DE.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/DE-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NJ.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NJ-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/PR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/PR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/VT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/VT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NH.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NH-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MD.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MD-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/IN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/IN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/SC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/SC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/OH.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/OH-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/WV.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/WV-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/ME.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/ME-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/PA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/PA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MS.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MS-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/HI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/HI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/AR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/AR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/IA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/IA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/AL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/AL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/TN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/TN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/ND.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/ND-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/IL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/IL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/KY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/KY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/LA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/LA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/KS.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/KS-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/WI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/WI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/GA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/GA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/SD.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/SD-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/WA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/WA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NE.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NE-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/VA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/VA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MO.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MO-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/OK.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/OK-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/UT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/UT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/WY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/WY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/CO.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/CO-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NM.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NM-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/AZ.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/AZ-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/OR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/OR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/ID.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/ID-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NV.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/NV-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/MT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/FL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/FL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/CA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/CA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/TX.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/TX-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/CT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/CT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/AK.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs/AK-no-rivers.json
