python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/DC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/DC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/GU.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/GU-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/RI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/RI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/VI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/VI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/DE.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/DE-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/CT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/CT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NJ.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NJ-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/PR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/PR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/VT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/VT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NH.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NH-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MD.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MD-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/IN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/IN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/WV.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/WV-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/SC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/SC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/OH.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/OH-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/PA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/PA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/ME.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/ME-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MS.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MS-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/IA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/IA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/TN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/TN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MP.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MP-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/ND.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/ND-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/KY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/KY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/IL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/IL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/KS.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/KS-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/LA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/LA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/GA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/GA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/SD.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/SD-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NE.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NE-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/WA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/WA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/VA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/VA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/WI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/WI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AS.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AS-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MO.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MO-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/OK.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/OK-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/UT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/UT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/WY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/WY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/CO.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/CO-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NM.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NM-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AZ.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AZ-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/OR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/OR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/ID.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/ID-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NV.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/NV-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/MT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/FL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/FL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/CA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/CA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/TX.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/TX-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/HI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/HI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AK.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_500m/AK-no-rivers.json
