python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/DC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/DC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/DC-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/DC-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/RI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/RI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/RI-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/RI-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VI-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VI-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/DE.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/DE-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/DE-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/DE-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CT-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CT-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NJ.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NJ-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NJ-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NJ-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/PR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/PR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/PR-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/PR-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VT-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VT-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NH.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NH-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NH-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NH-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MA-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MA-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MD.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MD-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MD-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MD-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IN-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IN-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WV.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WV-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WV-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WV-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/SC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/SC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/SC-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/SC-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OH.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OH-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OH-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OH-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/PA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/PA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/PA-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/PA-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ME.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ME-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ME-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ME-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MS.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MS-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MS-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MS-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AR-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AR-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IA-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IA-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AL-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AL-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/TN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/TN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/TN-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/TN-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ND.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ND-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ND-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ND-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/KY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/KY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/KY-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/KY-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IL-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/IL-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/KS.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/KS-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/KS-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/KS-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/LA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/LA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/LA-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/LA-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/GA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/GA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/GA-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/GA-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/SD.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/SD-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/SD-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/SD-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NE.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NE-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NE-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NE-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WA-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WA-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NC.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NC-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NC-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NC-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VA-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/VA-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WI-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WI-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MO.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MO-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MO-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MO-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OK.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OK-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OK-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OK-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/UT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/UT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/UT-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/UT-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WY-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/WY-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CO.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CO-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CO-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CO-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NY.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NY-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NY-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NY-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MN.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MN-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MN-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MN-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NM.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NM-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NM-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NM-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AZ.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AZ-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AZ-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/AZ-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OR.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OR-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OR-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/OR-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ID.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ID-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ID-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/ID-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NV.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NV-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NV-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/NV-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MI.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MI-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MI-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MI-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MT.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MT-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MT-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/MT-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/FL.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/FL-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/FL-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/FL-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CA.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CA-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CA-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/CA-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/TX.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/TX-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/TX-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/TX-single-print.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/usa_48.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/usa_48-no-rivers.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/usa_48-thru-river-cutout-base.json
python ./TouchTerrain_standalone.py ./touch_terrain_configs_250m/usa_48-single-print.json
